#!/bin/bash

set -e
set -x

PROGRAM_NAME="wirescale"

pip install -r /working_dir/requirements.txt

cp -r /working_dir/"$PROGRAM_NAME" /"$PROGRAM_NAME"
pyinstaller --add-data /working_dir/scripts:scripts  --onefile /"$PROGRAM_NAME"/__main__.py
mkdir -p /working_dir/dist
staticx /dist/__main__ /working_dir/dist/"$PROGRAM_NAME"

chown -R "$USERID":"$GROUPID" /working_dir/dist
chmod -R 755 /working_dir/dist
